# Generated by Django 2.1.5 on 2019-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffebene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'CAFFEBENE',
            },
        ),
        migrations.CreateModel(
            name='Ediya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'EDIYA',
            },
        ),
        migrations.CreateModel(
            name='Gongcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'GONGCHA',
            },
        ),
        migrations.CreateModel(
            name='Juicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'JUICY',
            },
        ),
        migrations.CreateModel(
            name='Momstouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MOMSTOUCH',
            },
        ),
        migrations.CreateModel(
            name='Mrsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MRSD',
            },
        ),
        migrations.CreateModel(
            name='Sinjeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SINJEON',
            },
        ),
        migrations.CreateModel(
            name='Starbucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'STARBUCKS',
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SUBWAY',
            },
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='author',
        ),
        migrations.DeleteModel(
            name='Franchise',
        ),
    ]
