# Generated by Django 2.2.3 on 2019-08-13 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
