# Generated by Django 2.2.3 on 2019-08-13 02:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='내용'),
        ),
    ]
