# Generated by Django 2.2.3 on 2019-08-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20190813_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='body',
            new_name='content',
        ),
    ]
