# Generated by Django 2.1.5 on 2019-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('price', models.IntegerField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
